import jsPDF from 'jspdf'

export function exportToPdf(title: string, content: string, filename: string) {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20

    // Title
    doc.setFontSize(18)
    doc.setTextColor(13, 148, 136) // teal
    doc.text(title, margin, 25)

    // Subtitle
    doc.setFontSize(10)
    doc.setTextColor(100, 116, 139) // muted
    doc.text(`CivicPulse Atlas Edition — ${new Date().toLocaleDateString()}`, margin, 33)

    // Divider
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, 37, pageWidth - margin, 37)

    // Content
    doc.setFontSize(11)
    doc.setTextColor(30, 30, 30)
    const lines = doc.splitTextToSize(content, pageWidth - margin * 2)

    let y = 45
    for (const line of lines) {
        if (y > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage()
            y = 20
        }
        doc.text(line, margin, y)
        y += 6
    }

    // Footer
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(160, 160, 160)
        doc.text(
            `Generated by CivicPulse Atlas — Page ${i} of ${pageCount}`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        )
    }

    doc.save(`${filename}.pdf`)
}
